main.ts
Hi,
I ran into an issue related to the crate name of a project. As hyphens are not allowed in package names, Rust [replaces](https://stackoverflow.com/a/60795534) them with underscores. As a result, wasmbuild tries to invoke `wasm-bindgen` on a file that does not exist (assuming hyphens instead of underscores) when a crate's name includes hyphens. This quick PR fixes that. Not sure if you're accepting PRs for this repository at this time (I see no contributing guidelines). Feel free to close this PR if you're not accepting PRs or if this is not the desired way of fixing this problem.
=> fix: accommodate for hyphens in crate names

README.md, main.ts
=> feat: remove need for `rustup target add wasm32-unknown-unknown` install step

README.md, main.ts, tests/.gitignore, tests/lib/deno_test.generated.js, tests/lib/snippets/deno_test-0783d0dd1a7e0cd8/add.js, tests/test.ts
=> feat: remove top level await and lazily construct module

README.md, main.ts, manifest.ts, tests/test.ts
Adds some cargo CLI arguments and an `--out <dir-path>` argument.
=> feat: add cargo cli arguments

README.md, lib/wasmbuild.generated.js, main.ts, tests/lib/deno_test.generated.js
I think we just need to add some conditionals here to get this working for the browser.
=> feat: support wasmbuild output in the browser

lib/new_command.ts
I was using this and found a few bugs.
=> fix(new_command): move .gitignore to root

lib/commands/build_command.ts, lib/pre_build.ts
Please, please, spell it correctly...
Reference: [WebAssembly official website](https://webassembly.org/)
=> chore: fix spelling of "WebAssembly"

lib/args.ts, lib/commands/build_command.ts
fix #44 
Based on #44, I fixed optimization is no longer performed with debug flag.
=> fix: skip optimizing when running with --debug

README.md, lib/pre_build.ts, tests/lib/deno_test.generated.js, tests/lib_sync/deno_test.generated.js, tests/test.ts
=> feat: ability to provide custom url to wasm file

lib/pre_build.ts, lib/wasmbuild.generated.js
What happens when I work in meetings.
=> fix: wasm_url to wasmUrl

lib/pre_build.ts, lib/wasmbuild.generated.js
Now I've actually tested this....
=> fix: transform -> decompress

lib/args.ts, lib/pre_build.ts, main.ts
Just an idea to maybe improve the current situation
Add a check for the presence of Cargo.toml
Add --help option
=> feat: add help command and improve setup dx

lib/commands/new_command.ts
fix https://github.com/denoland/wasmbuild/issues/48
=> feat: check available tools in new command

lib/pre_build.ts
=> fix: quote rustflags

loader.ts
Closes https://github.com/denoland/wasmbuild/issues/92
=> fix: prevent type checking errors with dnt

lib/commands/new_command.ts
=> fix(new): update workspace resolver in generated Cargo.toml

README.md, lib/commands/new_command.ts
1. Puts the simpler example first
2. Splits up the tests
3. Use JS instead of TS in the output so that people can try this right away in browsers
=> fix: slightly improve scaffolding

lib/commands/new_command.ts
Swaps based on usage in the file.
=> chore: swap variables

.github/workflows/ci.yml
Fix publish for next time. Going to do it manually.
=> chore: fix publish

lib/versions.test.ts, lib/versions.ts
=> chore: document reasoning behind version checks

lib/pre_build.ts
Use `CARGO_ENCODED_RUSTFLAGS` instead of `RUSTFLAGS` to pass flags to rustc, and fix incorrect quoting of our remapped path flags. This change allows arguments (including the ones added internally for `--remap-path-prefix`) to included space characters without causing errors.
If users of wasmbuild provide their own flags through `RUSTFLAGS`, they will be merged into our `CARGO_ENCODED_RUSTFLAGS` value, to match the existing behaviour of wasmbuild. If they provide flags through `CARGO_ENCODED_RUSTFLAGS`, those will take precedence and `RUSTFLAGS` will be ignored, in order to match [Cargo's precedence behaviour when both are specified](https://github.com/rust-lang/cargo/blob/07ac23a71c3005638ba7e9e43433f8db6963c9ba/src/cargo/core/compiler/build_context/target_info.rs#L744-L766).
(Note that …
=> fix: use CARGO_ENCODED_RUSTFLAGS instead of RUSTFLAGS to pass flags to rustc

.github/workflows/ci.yml
=> fix: ci.yml
